import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <img
          src="/papel-llogoo.png"
          alt="logo"
          className="absolute top-8 w-[50px] left-12 xs:max-md:w-[80px] xs:max-md:left-[9rem]"
        />
        {children}
      </body>
    </html>
  );
}
